package ers.group;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author fedoc
 */
public class Marksheettab extends javax.swing.JPanel {
    
    private List<Marksheet> marksheets;

    /**
     * Creates new form Marksheettab
     */
    public Marksheettab() {
        initComponents();
        marksheets = new ArrayList<>();
        loadMarksheetData();
        Searchbutton.addActionListener(this::SearchbuttonActionPerformed);
    }
    
    public static void main(String[] args) {
        System.out.println("Starting Marksheet Application...");
        SwingUtilities.invokeLater(() -> {
            try {
                JFrame frame = new JFrame("Student Marksheet System");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(1600, 900);
                frame.setLocationRelativeTo(null);
                frame.setResizable(true);
                frame.add(new Marksheettab());
                frame.setVisible(true);
                System.out.println("Application initialized successfully!");
            } catch (Exception e) {
                System.err.println("Error creating application: " + e.getMessage());
                e.printStackTrace();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        StudentIDPanel = new javax.swing.JPanel();
        StudentID = new javax.swing.JLabel();
        SearchbarID = new javax.swing.JTextField();
        Searchbutton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        GWA = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoretable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        printbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();

        Background.setBackground(new java.awt.Color(31, 58, 95));

        jPanel15.setBackground(new java.awt.Color(0, 30, 58));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        StudentIDPanel.setBackground(new java.awt.Color(0, 30, 58));
        StudentIDPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 216, 233), 4));

        StudentID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        StudentID.setForeground(new java.awt.Color(255, 255, 255));
        StudentID.setText("Student ID");

        SearchbarID.setBackground(new java.awt.Color(146, 190, 219));

        Searchbutton.setBackground(new java.awt.Color(189, 216, 233));
        Searchbutton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Searchbutton.setText("Search");
        Searchbutton.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout StudentIDPanelLayout = new javax.swing.GroupLayout(StudentIDPanel);
        StudentIDPanel.setLayout(StudentIDPanelLayout);
        StudentIDPanelLayout.setHorizontalGroup(
            StudentIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentIDPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(StudentIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentIDPanelLayout.createSequentialGroup()
                        .addComponent(SearchbarID, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        StudentIDPanelLayout.setVerticalGroup(
            StudentIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentIDPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(StudentID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchbarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Searchbutton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 30, 58));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 216, 233), 4));

        GWA.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        GWA.setForeground(new java.awt.Color(255, 255, 255));
        GWA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GWA.setText("GWA: --");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(GWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GWA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentIDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(StudentIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 30, 58));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        scoretable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student ID", "Semester", "Course 1", "Score 1", "Course 2", "Score 2", "Course 3", "Score 3", "Course 4", "Score 4", "Course 5", "Score 5", "Average"
            }
        ));
        scoretable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(scoretable);

        jPanel2.setBackground(new java.awt.Color(0, 30, 58));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        printbutton.setBackground(new java.awt.Color(73, 118, 159));
        printbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        printbutton.setText("Print");
        printbutton.setForeground(new java.awt.Color(0, 0, 0));
        printbutton.addActionListener(this::printbuttonActionPerformed);

        clearbutton.setBackground(new java.awt.Color(73, 118, 159));
        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.setForeground(new java.awt.Color(0, 0, 0));
        clearbutton.addActionListener(this::clearbuttonActionPerformed);

        logoutbutton.setBackground(new java.awt.Color(73, 118, 159));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.setForeground(new java.awt.Color(0, 0, 0));
        logoutbutton.addActionListener(this::logoutbuttonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(printbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void printbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
            scoretable.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error printing: " + e.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        SearchbarID.setText("");
        GWA.setText("GWA: --");
        DefaultTableModel model = (DefaultTableModel) scoretable.getModel();
        model.setRowCount(0);
    }                                           

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        SearchbarID.setText("");
        GWA.setText("GWA: --");
        DefaultTableModel model = (DefaultTableModel) scoretable.getModel();
        model.setRowCount(0);
        JOptionPane.showMessageDialog(this, "Logged out successfully", "Logout", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        String studentID = SearchbarID.getText().trim();
        
        if (studentID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        searchStudentMarks(studentID);
    }
    
    private void loadMarksheetData() {
        // Try multiple possible paths
        String[] possiblePaths = {
            "marksheet.txt",
            "ERS-group/marksheet.txt",
            "../marksheet.txt",
            "../../marksheet.txt",
            System.getProperty("user.dir") + File.separator + "marksheet.txt",
            System.getProperty("user.dir") + File.separator + "ERS-group" + File.separator + "marksheet.txt"
        };
        
        File marksheetFile = null;
        for (String path : possiblePaths) {
            File f = new File(path);
            if (f.exists()) {
                marksheetFile = f;
                System.out.println("Found marksheet at: " + f.getAbsolutePath());
                break;
            }
        }
        
        if (marksheetFile == null) {
            System.out.println("Marksheet file not found in any of the expected locations");
            System.out.println("Current working directory: " + System.getProperty("user.dir"));
            return;
        }
        
        try (Scanner scanner = new Scanner(marksheetFile)) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine().trim();
                if (line.isEmpty()) continue;
                
                String[] parts = line.split(",");
                if (parts.length >= 13) {
                    String studentID = parts[0].trim();
                    String studentName = parts[1].trim();
                    String schoolYear = parts[2].trim();
                    String semester = parts[3].trim();
                    
                    String[] subjects = new String[5];
                    double[] marks = new double[5];
                    
                    // Parse 5 courses and their marks
                    for (int i = 0; i < 5; i++) {
                        int baseIdx = 4 + (i * 3);
                        if (baseIdx < parts.length) {
                            subjects[i] = parts[baseIdx].trim();
                            try {
                                marks[i] = Double.parseDouble(parts[baseIdx + 1].trim());
                            } catch (NumberFormatException e) {
                                marks[i] = 0;
                            }
                        }
                    }
                    
                    marksheets.add(new Marksheet(studentID, studentName, schoolYear, semester, subjects, marks));
                }
            }
            System.out.println("Loaded " + marksheets.size() + " marksheet records");
        } catch (Exception e) {
            System.out.println("Error loading marksheet: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void searchStudentMarks(String studentID) {
        DefaultTableModel model = (DefaultTableModel) scoretable.getModel();
        model.setRowCount(0);
        
        List<Marksheet> studentMarks = new ArrayList<>();
        for (Marksheet m : marksheets) {
            if (m.getStudentID().equals(studentID)) {
                studentMarks.add(m);
            }
        }
        
        if (studentMarks.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No records found for Student ID: " + studentID, "Not Found", JOptionPane.INFORMATION_MESSAGE);
            GWA.setText("GWA: --");
            return;
        }
        
        double totalGWA = 0;
        int rowNum = 0;
        
        for (Marksheet m : studentMarks) {
            String[] subjects = m.getSubjects();
            double[] marks = m.getMarks();
            double average = calculateAverage(marks);
            totalGWA += average;
            
            Object[] row = new Object[14];
            row[0] = rowNum + 1;
            row[1] = m.getStudentID();
            row[2] = m.getSemester();
            row[3] = subjects[0];
            row[4] = marks[0];
            row[5] = subjects[1];
            row[6] = marks[1];
            row[7] = subjects[2];
            row[8] = marks[2];
            row[9] = subjects[3];
            row[10] = marks[3];
            row[11] = subjects[4];
            row[12] = marks[4];
            row[13] = String.format("%.2f", average);
            
            model.addRow(row);
            rowNum++;
        }
        
        double finalGWA = studentMarks.size() > 0 ? totalGWA / studentMarks.size() : 0;
        GWA.setText(String.format("GWA: %.2f", finalGWA));
    }
    
    private double calculateAverage(double[] marks) {
        double sum = 0;
        for (double mark : marks) {
            sum += mark;
        }
        return marks.length > 0 ? sum / marks.length : 0;
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JPanel Background;
    private javax.swing.JLabel GWA;
    private javax.swing.JTextField SearchbarID;
    private javax.swing.JButton Searchbutton;
    private javax.swing.JLabel StudentID;
    private javax.swing.JPanel StudentIDPanel;
    private javax.swing.JButton clearbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton printbutton;
    private javax.swing.JTable scoretable;
    // End of variables declaration                   
}
